export const USER_INFO_URL = {
  USER_REGISTER: "account/auth/trading/register",
  SEND_MAIL: "account/auth/trading/send/mail",
  RESEND_MAIL: "account/auth/trading/resend/mail",
  GEETEST_INIT: "account/auth/init",
  GEETEST_VALIDATE: "account/auth/validate",
  // GEETEST_INIT: "account/init",
  // GEETEST_VALIDATE: "account/validate",
  CONFIRM_MAIL: "account/auth/trading/confirm/mail",
  ADD_ACCOUT: "account/protected/subaccounts/add",
  LOGIN: "account/auth/trading/login",
  REST_PASSWORD: "account/protected/trading/reset/password",
  ACCOUT_LIST: "account/protected/subaccounts/list",
  CHNAGE_ACCOUT_MESSAGE: "account/protected/subaccounts/update",
  ACCOUT_DELETE: "account/protected/subaccounts/del/",
  SUB_ACCOUNT_LIST: "account/protected/trading/get/subAccounts",
  ALL_LOGIN: "account/protected/managements/logins/list",
  BIND_DEFAULT: "account/protected/managements/accounts/default/bind",
  CREATE_LOGIN_ACCOUNT: "account/protected/add/loginAccount",
  GET_SUB_ACCOUNT: "account/protected/managements/accounts/combos",
  ADD_BIND: "account/protected/add/bind",
  IS_FREEZE: "account/protected/freeze/account",
  CREATE_APIKEY: "account/protected/trading/create/apiKey",
  GET_APIKEY: "account/protected/trading/apiKeys",
  ALL_ACCOUNTS: "account/protected/accounts/normal/list",
  DEL_APIKEY: "account/protected/trading/delete/apiKey",
  MANAGEMENT_REST_PASSWORD: "account/protected/reset/password",
  DELETE_LOGIN_ACCOUNT: "account/protected/account/del/",
  UPDATE_PERMISSION: "account/protected/update/permission",
  UN_BIND: "account/protected/account/unBind",
  SWITCH_ACCOUT: "account/protected/trading/switch/account",
  CHANGE_PERMISSION: "account/protected/trading/apiKey/change/permission",
  TOTAL_API_KEY: "account/protected/trading/apiKeys/total",
  USER_DATA: "account/protected/current/login",
  DATA_GET_SUBACCOUNT: "account/protected/accounts/pages",
  BLANCES_CHART: "account/protected/dashboard",
  SECURITY_TFA: "account/protected/tfa/protects/update",
  SECURITY_LIST: "account/protected/management/activity/account/find",
  SECURITY_TFA_TRUE: "account/protected/tfa/protected/update/true",
  SECURITY_TFA_FALSE: "account/protected/tfa/protected/update/false",
  DISABLE_TFA: "account/protected/tfa/enables/update",
  TAB_SUBACCOUNT: "account/protected/account/permission",
  ESTIMATED_BALANCE: "account/protected/estimated/balance",
  USER_BALANCE: "account/protected/balance/info",
  USER_POSITION: "account/protected/position/info/",
  TFA_BIND: "account/protected/tfa/bind",
  TFA_VALID: "account/protected/tfa/bind/valid",
  LOGIN_TFA: "account/tfa/login/v2",
  TRAD_FEE: "account/protected/trading/fee",
  TRAD_LEVEL: "account/protected/trading/account/level",
  ACCS_GET: "pricing/protected/accstat/get",
  ACCS_GPDAY: "pricing/protected/accstat/gpday",
  TRANSFER_ACCOUNT: "account/protected/transfers/accounts/combos",
  TRANSFER_COIN: "account/protected/transfers/collateral/combos",
  TRANSFER_SUBMIT: "account/protected/transfers/transfer",
  ALL_COIN: "account/protected/deposit/coin/",
  COIN_BALANCE: "account/protected/deposit/address",
  REST_PASSWORD_AUTH: "account/auth/find/tfa/type",
  SEVEN_HISTORY: "account/protected/recent/deposit/histories",
  TRANSFER_HISTORY: "account/protected/transfers/history/week",
  DIPOSIT_HISTORIES: "account/protected/deposit/histories",
  TRANSFERS_HISTORIES: "account/protected/transfers/history/list",
  EXPORT_DEPOSIT: "account/protected/export/deposit",
  EXPORT_TRANSFERS: "account/protected/transfers/history/export",
  WITHDRAW_HISTORY: "account/protected/recent/withdraw/histories",
  EXPORT_WITHDRAW: "account/protected/export/withdraw/histories",
  GET_WITHDRAW_ADDRESS: "account/protected/withdraw/network/address",
  SAVE_ADDRESS: "account/protected/save/withdraw/address",
  HAVE_POSITION: "account/protected/position/check",
  SUBMIT_WITHDRAW: "account/protected/withdraw",
  GET_ADDRESS: "account/protected/withdraw/addresses",
  HISTORIES_LIST: "account/protected/withdraw/histories",
  DELETE_ADDRESS: "account/protected/withdraw/address/delete",
  WITHDRAW_FEE: "account/protected/withdraw/fee/",
  LOGIN_OUT: "account/auth/trading/logout",
  GET_BALANCE: "account/protected/withdraw/balance/",
  GET_DEPOSIT_BALANCE: "account/protected/deposit/balance/",
  WITHDRAW_LIMIT: "account/protected/withdraw/limit",
  CHECK_ADDRESS: "account/protected/validate/address",
  DELIVERS_LIST: "delivery/protected/delivers/trades",
  MARKETS_TYPE: "markets/public/markets",
  GEETEST_TYPE: "account/protected/geetest",
  SPOT_HISTORY: "interohlc/protected/spot/trades",
  TRANSACTION_HISTORIES: "account/protected/transaction/histories",
  EXPORT_DELIVER: "delivery/protected/export/delivers/trades",
  EXPORT_TRANSACTION: "account/protected/export/transaction",
  EXPORT_FLEXCONVERT: "account/protected/converts/flexs/export",
  EXPORT_REPAY: "lending/protected/flex/export/repay/history",
  EXPORT_MOONPAY: "accvalue/protected/export/moonpay/histories",
  GET_SPREAD: "interohlc/protected/spread/trades",
  GET_REPO: "interohlc/protected/repo/trades",
  FUTURES_HISTORY: "interohlc/protected/futures/trades",
  FUNDING_HISTORY: "account/protected/funding/payments",
  GET_MARKETS: "markets/public/markets/base",
  EXPORT_SPOT: "interohlc/protected/export/spot/trades",
  EXPORT_FUTURE: "interohlc/protected/export/futures/trades",
  EXPORT_SPREAD: "interohlc/protected/export/spread/trades",
  EXPORT_REPO: "interohlc/protected/export/repo/trades",
  FUTURES_TYPES: "account/protected/futures/types",
  SWITCH_WHITELIST: "account/protected/",
  ADD_WHITE_ADDRESS: "account/protected/withdraw/add/white/list",
  REMOVE_WHITE_ADDRESS: "account/protected/withdraw/remove/white/list",
  FUNDING_HISTORY_PAGE: "delivery/public/auctions/find/page",
  TRANSACTION_TYPE: "account/protected/transaction/types",
  GET_AUTHORIZE: "auth/oauth/authorize",
  GEETST_ACCOUNT: "account/auth/confirm/geetest",
  REFERRAL_LIST: "account/protected/referral/record",
  SHARE_INFO: "account/protected/share/user/info",
  REBATES: "account/protected/rebates/records",
  SPOT_TYPE: "account/protected/spot/types",
  GET_VOTE_COIN: "account/public/vote/coins",
  GET_VOTE_PROFILE: "account/public/vote/profile",
  GET_VOTE_BALANCE: "account/protected/vote/balance/snapshots/",
  SUBMIT_VOTED: "account/protected/vote",
  GET_FEE: "account/protected/withdraw/fees",
  GET_NETWORK: "markets/protected/coins/get/",
  GET_FLEXASSET: "lending/protected/flex/asset/history",
  GET_HISTORY_ACCOUNT_LIST: "account/protected/account/relations",
  EXPORT_ASSET_HISTORY: "lending/protected/export/flex/asset/history",
  GET_HISTORY_BORROW: "lending/protected/flex/asset/borrow/history",
  GET_HISTORY_REPAY: "lending/protected/flex/asset/borrow/repay/infos",
  GET_BORROW_REPAY_TYPE: "lending/public/flex/asset/coin",
  CLOSE_BORROW: "lending/protected/borrow/close",
  VALI_DEPOSIT_COIN: "markets/public/instruments/coins/base/deposit",
  VALI_WITHDRAW_COIN: "markets/public/instruments/coins/base/withdrawal",
  SETTING_INDEX: "account/protected/settlement/index/histories",
  SETTING_FUTURES: "interohlc/protected/settlement/futures/trades",
  GET_MIN_WITHDRAW: "account/protected/withdraw/amount/info",
  GET_KYC_INFO: "account/protected/kyc/information",
  SUBMIT_KYV_CORPORATE: "account/protected/kyc/corporate",
  SUBMIT_KTC_INDIVIDUAL: "account/protected/kyc/individual",
  UPDALOAD_KYC: "candles/protected/upload",
  GET_MARKETS_ALL: "markets/public/markets/all",
  GET_ACCCIRACY: "markets/public/sync/display/accuracy",
  ALL_COIN_LIST: "markets/protected/coin/claims",
  TRANSFER_BALANCES: "account/protected/balances?needDisplay=false&accountId=",
  NEW_WORTH: "accvalue/protected/asset/net/worth",
  GET_TODAY_PNL: "accvalue/protected/today/pnl",
  GET_DAILY_PNL: "accvalue/protected/daily/pnl/changes",
  CIRCULATING_SUPPLY: "accvalue/public/flex/chain/info",
  LINE_SUPPLY: "accvalue/public/flex/supply",
  GET_MARKET_INFO: "accvalue/public/flex/market/info",
  LINE_CAP: "accvalue/public/flex/market/cap",
  MAX_WITHDRAW: "account/protected/max/withdraw/amount/",
  US_KYC_UPLOAD: "account/protected/upload/us/kyc",
  US_KYC_UPDATE: "account/protected/update/us/kyc",
  GET_GOOGLE_FIILES: "dbworker/protected/download/kyc/",
  TFA_REMIND: "account/protected/tfa/reminds",
  GET_CODE: "account/auth/trading/qrlogin/get",
  QR_LOGIN_CHECK: "account/auth/trading/qrlogin/check",
  WALLET_AUTH_NONCE: "account/auth/metamask/users",
  WALLET_AUTH: "account/auth/metamask",
  VALIDATE_BIND_ADDRESS: "account/auth/validate/bind",
  BIND_METAMASK: "account/protected/bind/metamask",
  BIND_METAMASK_EMAIL: "account/protected/bind/email",
  VALIDATE_METAMASK_EMAIL_BIND_ADDRESS: "account/auth/validate/bind",
  ETH_GAS_PRICE: "account/protected/get/eth/gas",
  SEND_METAMASK_EMAIL_MAIL: "account/protected/confirm/code",
  GET_ANTI_STATUS: "account/protected/accounts/antiphish/get",
  CHANGE_ANTI_NAME: "account/protected/accounts/antiphish/bound",
  FETCH_REWARD: "competition/protected/reward/history",
  FETCH_RECEIVE: "competition/protected/get/sign/in/rewards?rewardId=",
  GET_MARKET: "markets/public/markets",
  GET_CONVERT_FLEX: "account/protected/converts/flexs/combo",
  CONVERT_FLEX: "account/protected/converts/flexs",
  GET_CONVERT_FLEX_HISTORY: "account/protected/converts/flexs/page",
  GET_TYPE: "account/protected/tfa/types",
  MOONPAY_DEPOSIT_ADDRESS: "account/protected/moonpay/deposit/addresses",
  ALL_AMM: "amm/protected/amm/hash-token",
  TRADE_HISTORY: "interohlc/protected/amm/trade/history",
  OPEN_ORDER: "amm/protected/amm/open/order/",
  INTEREST_PAYMENT: "amm/protected/amm/interest/payment",
  TRANSFER_IN_OUT: "amm/protected/amm/transfer/in-out",
  BORROW_LIQUIDATION: "amm/protected/amm/liquidation/borrow",
  EXPORT_AMM_TRADE_HISTORY: "interohlc/protected/export/amm/trade/history",
  EXPORT_AMM_OPEN_ORDERS: "amm/protected/export/amm/open/orders",
  EXPORT_AMM_INTEREST_PAYMENT: "amm/protected/export/amm/interest/payment",
  EXPORT_AMM_BORROW_LIQUIDATION: "amm/protected/export/amm/liquidation/borrow",
  EXPORT_AMM_TRANSFER_IN_OUT: "amm/protected/export/amm/transfer/in-out",
  WHITE_LIST_EMAIL: "account/protected/accounts/whitelist/switch/email",
  GET_MOONPAY_CURRENCIES: "v3/currencies",
  AGREE_MOONPAY: "account/protected/agree/moonpay",
  ALLOW_MOONPAY: "account/protected/moonpay/allow",
  MOONPAY_HISTORY: "accvalue/protected/moonpay/history",
  IS_USER_IP_US: "account/public/detect/account",
  SUBMIT_TOS: "account/protected/submit/submit-tos",
  SETTLEMENT_TRADES: "interohlc/protected/settlement/trades",
  KYC3_CRA: "account/protected/cra/",
  KYC3_CRA_ALL: "account/protected/cra/infos",
  KYC3_INFO: "account/protected/kyc3/info",
  SAVE_KYC3_INFO: "account/protected/save/kyc3",
  SUB_KYC3_INFO: "account/protected/submit/kyc3",
  DOWNLOAD_PIC: "dbworker/protected/download/encrypt/picture/?key=",
  UPLOAD_KYC3_PIC: "dbworker/protected/upload/picture/encrypt",
  GET_IP_BLOCK: "account/protected/ip/block/warning",
  GET_MARKET_DETAIL: "markets/public/markets/detail",
  GET_PERMISSIONS_RATE: "delivery/public/permissionless/funding-rate/page",
  WIHTDRAW_COIN_LIST: "account/protected/withdrawal/coin/dropdown/v2",
  DEPOSIT_COIN_LIST: "account/protected/deposit/coin/dropdown/v2",
  GOOGLE_LOGIN: "account/auth/google/login",
  PLP_FEE: "account/protected/trading/fee/plp",
  GET_IDENTITY_LINK: "account/protected/identity/documents/urls",
  GET_VERIFICATION_RESULT: "account/protected/id/verification/result",
  GET_SEEION_KEY: "account/protected/sardine/session/key",
  GET_SARDING_VERIFICATION: "account/protected/id/verification/status",
  GET_KYC_RESULT: "account/protected/kyc/compliance",
  GET_BANNER: "account/public/banner/",
  GET_SELECT_MARKET: "interohlc/public/market/name/",
  LEND_HISTORY: "mortgage/protected/lending/history/infos",
  BORROW_HISTORY: "mortgage/protected/borrow/history/infos",
  LEND_POOL: "mortgage/public/lending/pool/type",
  GET_FUNDING_HISTORY_EXCEL: "portal/public/export/auctions",
  GET_OUSD_HISTORY: "vault/protected/coin/convert/history",
  GET_VAULT_HISTORY: "vault/protected/vaultRecord/getRecordList",
};
const NO_TOKEN_URL = [
  {
    path: process.env.REACT_APP_HTTP_URL + "account/auth/trading/login",
  },
  {
    path: process.env.REACT_APP_HTTP_URL + "account/auth/trading/register",
  },
  {
    path: process.env.REACT_APP_HTTP_URL + "account/auth/trading/resend/mail",
  },
  {
    path: process.env.REACT_APP_HTTP_URL + "account/auth/trading/confirm/mail",
  },
  {
    path: process.env.REACT_APP_HTTP_URL + "account/init",
  },
  {
    path: process.env.REACT_APP_HTTP_URL + "account/auth/validate",
  },
  {
    path: process.env.REACT_APP_HTTP_URL + "account/auth/confirm/geetest",
  },
  {
    path: process.env.REACT_APP_HTTP_URL + "account/auth/validate/bind",
  },
];
export const checkToken = (url) => {
  for (let i = 0; i < NO_TOKEN_URL.length; i++) {
    if (NO_TOKEN_URL[i].path === url) {
      return true;
    }
  }
};
