export default {
  accoutListRefresh: false,
  users: {
    email: "",
    token: "",
    accountName: "",
    mainLogin: false,
  },
  isLogin: false,
  subAccounts: [],
  accountName: "",
  mainLogin: false,
  competitions: {
    all: [],
    joinable: [],
    past: [],
  },
  isWallet: false,
  allLoginAccount: [],
  dimensions: {},
  dashboardUserData: {},
  depositCoin: "USDT",
  withdrawCoin: "USDT",
  refresh: false,
  SwitchLanguage: "en",
  provider: null,
  loginActiveTab: "login",
  mateMaskSelectedAddress: "",
  ticker: [],
  tfaModalVisable: false,
  tfaList: [],
  kycInfo: {},
};
